### ISSUE TITLE
Missing itemCategories

### ISSUE THREAD

**Issue by Syrchalis** [erdelf/MinifyEverything#2]
Some minified buildings, (e.g. pod launcher or deadfall traps) don't get assigned an item category so they cannot be stored anywhere, becoming essentially unhaulable. Might be caused by other mods or load order, in this case a recommendation should be posted.

**Comment by erdelf** [comment]
Fair enough, they should probably get their own category.

**Comment by erdelf** [comment]
so... while trying to fix it I just realised, they can be stored easily. The building category makes no sense except with minified buildings and are controlled througgh that.
