### ISSUE TITLE
Strange error when trying to add/remove things from "Disabled Minifying For:" List

### ISSUE THREAD

**Issue by TenshiAkari12** [erdelf/MinifyEverything#3]
Hi! I'm not exactly sure why this suddenly started to happen, I never had issues with this mod before recently when I started back to playing B18 again, but for whatever reason, I get this red error when trying to add an item to the Disabled Minifying For list:

```
[HugsLib][ERR] Exception during DoWindowContents: System.MissingFieldException: Field 'RimWorld.ThingDefGenerator_Buildings.BlueprintDefNamePrefix' not found.
  at MinifyEverything.MinifyMod.DoSettingsWindowContents (Rect inRect) [0x00000] in <filename unknown>:0 
  at RimWorld.Dialog_VanillaModSettings.DoWindowContents (Rect inRect) [0x00000] in <filename unknown>:0 
Verse.Log:Error(String)
HugsLib.Utils.ModLogger:ReportException(Exception, String, Boolean, String)
RimWorld.Dialog_VanillaModSettings:DoWindowContents(Rect)
Verse.<WindowOnGUI>c__AnonStorey0:<>m__0(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)
```

And this one appears when removing one:

```
Adding duplicate Verse.ThingDef name: Bed_Blueprint_Install
Verse.Log:Error(String)
Verse.DefDatabase`1:Add(ThingDef)
MinifyEverything.MinifyEverything:AddMinifiedFor(ThingDef)
MinifyEverything.MinifyMod:DoSettingsWindowContents(Rect)
RimWorld.Dialog_VanillaModSettings:DoWindowContents(Rect)
Verse.<WindowOnGUI>c__AnonStorey0:<>m__0(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)
```

In the first error, the window actually loses the UI and changes the window to display that error as well, but it shows it takes the changes once you reopen the Options for ME again. With the second error, the UI still stays intact & removes the item, but the error console still pops up. 

I've tried with and without other mods... and the result is the same, regardless if its Modded or Vanilla objects. I'm absolutely confused. I've only updated to the most recent version of this again just to be sure and I know there's not another B18 update for Hugs' Library, and I haven't touched any other files in the game directory...

Perhaps you can offer some insight on this? Thanks in advance!

**Comment by erdelf** [comment]
somehow I never saw this issue.... but yeah, can't replicate in the current version so I'll assume it got fixed along the way until I get a new report.
